
[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "normal"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ResetFontSize"
key = 0
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 5

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true

[general]
live_config_reload = true

# [window.dimensions]
# columns = 100
# lines = 40
