local mainMod = "SUPER"

hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("flatpak run io.bassi.Amberol"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("librewolf -P ricardo"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("librewolf -P firma"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("ghostty --title=galc -e qalc"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("ghostty --title=yazi -e yazi"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + G", hl.dsp.window.cycle_next({ next = true, floating = true }))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.center())
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.window.resize({ x = 1200, y = 1000 }))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("libreoffice --quickstart --nolockcheck"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("ghostty --title=pass -e pass ff"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("ghostty --title=pass -e pass 2fa"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("ghostty"))
hl.bind(mainMod .. " + MOD5 + T", hl.dsp.exec_cmd("ghostty --title=ghostty"))
hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("ghostty --title=tmux -e $HOME/.config/hypr/scripts/tmux.sh"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("ghostty --title=ghostty -e nvim"))
hl.bind(mainMod .. " + SHIFT + X", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/logout.sh"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("[fullscreen] librewolf -P whatsapp --kiosk https://web.whatsapp.com"))
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd("hyprlauncher"))
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })
hl.bind("XF86PowerOff", hl.dsp.exec_cmd("wlogout -P eDP-1 -m 400"))
hl.bind("Print", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/screenshot.sh"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -1%"), { repeating = true })
hl.bind("SHIFT + XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -10%"), { repeating = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +1%"), { repeating = true })
hl.bind("SHIFT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +10%"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"), { repeating = true })
hl.bind("SHIFT + XF86MonBrightnessDown", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/brigtness_lg.sh - 10"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set 10%+"), { repeating = true })
hl.bind("SHIFT + XF86MonBrightnessUp", hl.dsp.exec_cmd("$HOME/.config/hypr/scripts/brigtness_lg.sh + 10"), { repeating = true })

hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + r", hl.dsp.window.center())
hl.bind(mainMod .. " + SHIFT + r", hl.dsp.window.resize({ x = 1200, y = 1000 }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

local workspaceMod = "MOD5"

hl.bind(workspaceMod .. " + a", hl.dsp.focus({ workspace = 1 }))
hl.bind(workspaceMod .. " + s", hl.dsp.focus({ workspace = 2 }))
hl.bind(workspaceMod .. " + d", hl.dsp.focus({ workspace = 3 }))
hl.bind(workspaceMod .. " + f", hl.dsp.focus({ workspace = 4 }))
hl.bind(workspaceMod .. " + g", hl.dsp.focus({ workspace = 5 }))
hl.bind(workspaceMod .. " + h", hl.dsp.focus({ workspace = 6 }))
hl.bind(workspaceMod .. " + j", hl.dsp.focus({ workspace = 7 }))
hl.bind(workspaceMod .. " + k", hl.dsp.focus({ workspace = 8 }))

hl.bind(workspaceMod .. " + q", hl.dsp.focus({ workspace = 9 }))
hl.bind(workspaceMod .. " + w", hl.dsp.focus({ workspace = 10 }))
hl.bind(workspaceMod .. " + e", hl.dsp.focus({ workspace = 11 }))
hl.bind(workspaceMod .. " + r", hl.dsp.focus({ workspace = 12 }))
hl.bind(workspaceMod .. " + t", hl.dsp.focus({ workspace = 13 }))
hl.bind(workspaceMod .. " + y", hl.dsp.focus({ workspace = 14 }))
hl.bind(workspaceMod .. " + u", hl.dsp.focus({ workspace = 15 }))
hl.bind(workspaceMod .. " + i", hl.dsp.focus({ workspace = 16 }))

hl.bind(workspaceMod .. " + SHIFT + a", hl.dsp.window.move({ workspace = 1 }))
hl.bind(workspaceMod .. " + SHIFT + s", hl.dsp.window.move({ workspace = 2 }))
hl.bind(workspaceMod .. " + SHIFT + d", hl.dsp.window.move({ workspace = 3 }))
hl.bind(workspaceMod .. " + SHIFT + f", hl.dsp.window.move({ workspace = 4 }))
hl.bind(workspaceMod .. " + SHIFT + g", hl.dsp.window.move({ workspace = 5 }))
hl.bind(workspaceMod .. " + SHIFT + h", hl.dsp.window.move({ workspace = 6 }))
hl.bind(workspaceMod .. " + SHIFT + j", hl.dsp.window.move({ workspace = 7 }))
hl.bind(workspaceMod .. " + SHIFT + k", hl.dsp.window.move({ workspace = 8 }))

hl.bind(workspaceMod .. " + SHIFT + q", hl.dsp.window.move({ workspace = 9 }))
hl.bind(workspaceMod .. " + SHIFT + w", hl.dsp.window.move({ workspace = 10 }))
hl.bind(workspaceMod .. " + SHIFT + e", hl.dsp.window.move({ workspace = 11 }))
hl.bind(workspaceMod .. " + SHIFT + r", hl.dsp.window.move({ workspace = 12 }))
hl.bind(workspaceMod .. " + SHIFT + t", hl.dsp.window.move({ workspace = 13 }))
hl.bind(workspaceMod .. " + SHIFT + y", hl.dsp.window.move({ workspace = 14 }))
hl.bind(workspaceMod .. " + SHIFT + u", hl.dsp.window.move({ workspace = 15 }))
hl.bind(workspaceMod .. " + SHIFT + i", hl.dsp.window.move({ workspace = 16 }))
