hl.on("hyprland.start", function()
	hl.exec_cmd("$HOME/.config/hypr/scripts/xdg-desktop-hyprland.sh")
	hl.exec_cmd("bus-update-activation-environment --systemd -all")
	hl.exec_cmd("ystemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("wsm app -- hypridle &")
	hl.exec_cmd("wsm app -- $HOME/.local/bin/hyprpolkitagent &")
	hl.exec_cmd("wsm app -- waybar &")
	hl.exec_cmd("wsm app -- swaync &")
	hl.exec_cmd("wsm app -- wlsunset -t 3500K -l -25 -L -49 &")
	hl.exec_cmd("HOME/.config/hypr/scripts/btconnect.sh &")
	hl.exec_cmd("HOME/.config/hypr/scripts/wpaperd.sh &")
end)
