-- $mainMod = SUPER
--
-- bind = $mainMod, A, exec, flatpak run io.bassi.Amberol
-- bind = $mainMod, B, exec, librewolf -P ricardo
-- bind = $mainMod SHIFT, B, exec, librewolf -P firma
-- bind = $mainMod, C, exec, ghostty --title=galc -e qalc
-- bind = $mainMod, E, exec, ghostty --title=yazi -e yazi
-- bind = $mainMod, F, fullscreen
-- bind = $mainMod SHIFT, G, togglefloating,
-- bind = $mainMod, G, cyclenext, floating
-- bind = $mainMod ALT, H, exec, hyprpicker -a
-- bind = $mainMod SHIFT, Q, killactive,
-- bind = $mainMod, O, exec, libreoffice --quickstart --nolockcheck
-- bind = $mainMod, P, exec, ghostty --title=pass -e pass ff
-- bind = $mainMod SHIFT, P, exec, ghostty --title=pass -e pass 2fa
-- bind = $mainMod, R, resizeactive, exact 1200 1000
-- bind = $mainMod, T, exec, ghostty
-- bind = $mainMod MOD5, T, exec, ghostty --title=ghostty
-- bind = $mainMod SHIFT, T, exec, ghostty --title=tmux -e $HOME/.config/hypr/scripts/tmux.sh
-- bind = $mainMod, V, exec, ghostty --title=ghostty -e nvim
-- bind = $mainMod SHIFT, X, exec, $HOME/.config/hypr/scripts/logout.sh
-- bind = $mainMod, W, exec, [fullscreen] librewolf -P whatsapp --new-window https://web.whatsapp.com
-- bind = $mainMod, RETURN, exec, tofi-drun --drun-launch=true
-- bindl= ,switch:Lid Switch, exec, systemctl suspend
-- bind = ,XF86PowerOff, exec, wlogout -P eDP-1 -m 400
-- bind = ,Print, exec, $HOME/.config/hypr/scripts/screenshot.sh
-- bind = ,XF86AudioMute, exec, pactl set-sink-mute @DEFAULT_SINK@ toggle
-- bind = ,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -1%
-- bind = SHIFT,XF86AudioLowerVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ -10%
-- bind = ,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +1%
-- bind = SHIFT,XF86AudioRaiseVolume, exec, pactl set-sink-volume @DEFAULT_SINK@ +10%
-- bind = ,XF86AudioMicMute, exec, pactl set-source-mute @DEFAULT_SOURCE@ toggle
-- bind = ,XF86AudioPlay, exec, playerctl play-pause
-- bind = ,XF86AudioPause, exec, playerctl pause
-- bind = ,XF86AudioNext, exec, playerctl next
-- bind = ,XF86AudioPrev, exec, playerctl previous
-- bind = ,XF86MonBrightnessDown, exec, brightnessctl set 10%-
-- bind = SHIFT,XF86MonBrightnessDown, exec, $HOME/.config/hypr/scripts/brigtness_lg.sh - 10
-- bind = ,XF86MonBrightnessUp, exec, brightnessctl set 10%+
-- bind = SHIFT,XF86MonBrightnessUp, exec, $HOME/.config/hypr/scripts/brigtness_lg.sh + 10
--
-- bind = $mainMod, h, movefocus, l
-- bind = $mainMod, l, movefocus, r
-- bind = $mainMod, k, movefocus, u
-- bind = $mainMod, j, movefocus, d
--
-- bind = $mainMod SHIFT, h, movewindow, l
-- bind = $mainMod SHIFT, l, movewindow, r
-- bind = $mainMod SHIFT, k, movewindow, u
-- bind = $mainMod SHIFT, j, movewindow, d
-- bind = $mainMod SHIFT, n, centerwindow
--
-- bindm = $mainMod, mouse:272, movewindow
-- bindm = $mainMod, mouse:273, resizewindow
--
-- $workspaceMod = MOD5
--
-- bind = $workspaceMod, a, workspace, 1
-- bind = $workspaceMod, s, workspace, 2
-- bind = $workspaceMod, d, workspace, 3
-- bind = $workspaceMod, f, workspace, 4
-- bind = $workspaceMod, g, workspace, 5
-- bind = $workspaceMod, h, workspace, 6
-- bind = $workspaceMod, j, workspace, 7
-- bind = $workspaceMod, k, workspace, 8
--
-- bind = $workspaceMod SHIFT, a, movetoworkspace, 1
-- bind = $workspaceMod SHIFT, s, movetoworkspace, 2
-- bind = $workspaceMod SHIFT, d, movetoworkspace, 3
-- bind = $workspaceMod SHIFT, f, movetoworkspace, 4
-- bind = $workspaceMod SHIFT, g, movetoworkspace, 5
-- bind = $workspaceMod SHIFT, h, movetoworkspace, 6
-- bind = $workspaceMod SHIFT, j, movetoworkspace, 7
-- bind = $workspaceMod SHIFT, k, movetoworkspace, 8
