#!/usr/bin/env bash
show=()

if [ -e /home/ricardo/.monitor-opts-day ];then
    show+="*"
fi

if [ -e /home/ricardo/.xidleoff ];then
    show+="#"
fi

for disp in $(xrandr | sed -n 's/^\([^ ]*\).connected.*/\1/p'); do
    current=$(xrandr --verbose | grep $disp -A5 -m1 | grep "Brightness" | awk '{print $2}');

    show+=($(echo $current \* 100 | bc | cut -d'.' -f1)%)
    show+=' '
done

f() { show=("${BASH_ARGV[@]}"); }

shopt -s extdebug
f "${show[@]}"
shopt -u extdebug

echo "${show[@]}"
