#!/bin/bash
show=()
if [ $(pulsemixer --list-sinks | grep Default | cut -d',' -f3 | cut -d' ' -f3) == 1 ]; then
  #echo -n "Muted"
  show+=$(echo "Muted")
else
    show+=$(pulsemixer --list-sinks | grep Default | cut -d\' -f2)
fi

if [ $(pulsemixer --list-sources | grep Default | cut -d"," -f3 | cut -d" " -f3) == 1 ]; then
    show+=$(echo " / Muted")
fi

echo "${show[@]}"
